// export const URL_ADDRESS="https://markadmin-backend.herokuapp.com";
export const URL_ADDRESS = "https://markadmin-backend.vercel.app";
// export const URL_ADDRESS = "http://localhost:5000";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const UPDATE_PRODUCT_BY_ID = "UPDATE_PRODUCT_BY_ID";

export const GET_CONTACT = "GET_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const GET_CONTACT_BY_ID = "GET_CONTACT_BY_ID";
export const UPDATE_CONTACT_BY_ID = "UPDATE_CONTACT_BY_ID";

export const GET_CHOCOLATE_ORDER = "GET_CHOCOLATE_ORDER";
export const GET_CHOCOLATE_ORDER_BY_ID = "GET_CHOCOLATE_ORDER_BY_ID";
export const POST_CHOCOLATE_ORDER = "POST_CHOCOLATE_ORDER";
export const DELETE_CHOCOLATE_ORDER = "DELETE_CHOCOLATE_ORDER";
export const EDIT_CHOCOLATE_ORDER_BY_ID = "EDIT_CHOCOLATE_ORDER_BY_ID";
export const UPDATE_CHOCOLATE_ORDER_BY_ID = "UPDATE_CHOCOLATE_ORDER_BY_ID";

export const POST_ASSEMBLY = "POST_ASSEMBLY";
export const GET_ASSEMBLY = "GET_ASSEMBLY";
export const GET_ITEM_LIST = "GET_ITEM_LIST";
export const POST_ITEM_LIST = "POST_ITEM_LIST";
export const EDIT_ITEM_LIST_BY_ID = "EDIT_ITEM_LIST_BY_ID";
export const DELETE_ITEM_LIST_BY_ID = "DELETE_ITEM_LIST_BY_ID";
export const GET_INGREDIENT_LIST = "GET_INGREDIENT_LIST";
export const POST_INGREDIENT_LIST = "POST_INGREDIENT_LIST";
export const EDIT_INGERDIENT_LIST_BY_ID = "EDIT_INGERDIENT_LIST_BY_ID";
export const DELETE_INGERDIENT_LIST_BY_ID = "DELETE_INGERDIENT_LIST_BY_ID";
export const GET_EXPENSES_LIST = "GET_EXPENSES_LIST";
export const EDIT_EXPENSES_LIST_BY_ID = "EDIT_EXPENSES_LIST_BY_ID";
export const DELETE_EXPENSES_LIST_BY_ID = "DELETE_EXPENSES_LIST_BY_ID";
export const GET_RECIPE_LIST = "GET_RECIPE_LIST";
export const GET_RECIPE_LIST_BY_ID = "GET_RECIPE_LIST_BY_ID";
export const DELETE_RECIPE_LIST_BY_ID = "DELETE_RECIPE_LIST_BY_ID";
